## Numpy array operations

In [1]:
import numpy as np

### Indexing and Slicing

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Basic Slicing ", arr[2: 7]) # exclusive outer bound
print("With Step ", arr[1: 8: 2])
print("negative indexing ", arr[-3]) # starts with -1 from last element

Basic Slicing  [3 4 5 6 7]
With Step  [2 4 6 8]
negative indexing  8


### Indexing and Slicing 2D Array

In [7]:
arr_2d = np.array( [[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

print("Specific element ", arr_2d[2, 2])
print("Entire first row: ", arr_2d[0])
print("Entire first column ", arr_2d[ : , 0])
print("matrix row 1 to 2 and column 0 to 2 ", arr_2d[ 1: 3, 0 : 2])


Specific element  9
Entire first row:  [1 2 3]
Entire first column  [1 4 7]
matrix row 1 to 2 and column 0 to 2  [[4 5]
 [7 8]]


### Sorting

In [10]:
unsorted = np.array([3, 1, 4, 1, 5])
print("Sorted array ", np.sort(unsorted))

arr_2d_unsorted = np.array ( [ [3, 1,], [1, 2], [2, 3]])
print("Sorted 2d array by column ", np.sort(arr_2d_unsorted, axis= 0) )
print("Sorted 2d array by row ", np.sort(arr_2d_unsorted, axis= 1) )

Sorted array  [1 1 3 4 5]
Sorted 2d array by column  [[1 1]
 [2 2]
 [3 3]]
Sorted 2d array by row  [[1 3]
 [1 2]
 [2 3]]


### Filter

In [11]:
numbers = np.array( [1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_number = numbers[ numbers % 2 == 0 ]
odd_number = numbers[ numbers % 2 ==  1]
print("Even ", even_number)
print("Odd ", odd_number)

Even  [ 2  4  6  8 10]
Odd  [1 3 5 7 9]


### Filter with mask

In [12]:
mask = numbers > 5
print("Numbers greater than 5", numbers[mask])

Numbers greater than 5 [ 6  7  8  9 10]


### Fancy indexing vs np.where()

In [13]:
indices = [0, 2, 4]
print(numbers[ indices ])

[1 3 5]


In [ ]:
where_result = np.where(numbers > 5)
print(where_result) # stores indices of values > 5
print("NP where ", numbers[where_result])

(array([5, 6, 7, 8, 9]),)
NP where  [ 6  7  8  9 10]


In [16]:
condition_array = np.where(numbers > 5 , numbers * 2, numbers)
print("Multiply each element greater than 5 by 2 using where () ",condition_array)
original = np.where(numbers > 5, numbers * 1, numbers)
print("Original array from where ", original)

Multiply each element greater than 5 by 2 using where ()  [ 1  2  3  4  5 12 14 16 18 20]
Original array from where  [ 1  2  3  4  5  6  7  8  9 10]


condition_array = np.where(numbers > 5 , numbers * 2, numbers)
same as :
if(numbers > 5) {
    numbers * 2
} else {
    numbers
}

np.where(condition, truebody, falsebody)

### Adding and removing data

In [18]:
arr1 = np.array([ 1, 2, 3])
arr2 = np.array([4, 5, 6])

combined = np.concatenate( (arr1, arr2) )
print(combined)


[1 2 3 4 5 6]


### Array Compatibility

In [20]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6, 7])
c = np.array([7, 8, 9])

print("Compatibility shapes ", a.shape == b.shape)


Compatibility shapes  False


In [23]:
original = np.array([ [1, 2], [3, 4]])
new_row = np.array([5, 6])

with_new_row = np.vstack( (original, new_row) )
print("Original array ", original)
print("After adding new row ", with_new_row)

new_col = np.array( [[7], [8] ])
with_new_col = np.hstack((original, new_col))
print("After adding a new column ", with_new_col)

Original array  [[1 2]
 [3 4]]
After adding new row  [[1 2]
 [3 4]
 [5 6]]
After adding a new column  [[1 2 7]
 [3 4 8]]


### Deleting from np array

In [24]:
arr = np.array( [1, 2, 3,4 ,5])
deleted = np.delete(arr, 2)
print("Array after deletion ", deleted)

Array after deletion  [1 2 4 5]


### Deletion from 2D array

In [28]:
arr_2d_original = np.array( [ [1, 2, 3], [4, 5, 6 ],[ 7, 8, 9]])
row_to_dlt = [1, 2]
cols_to_dlt = [1, 2]

arr_2d_deleted = np.delete(arr_2d_original, row_to_dlt, axis = 0) # axis = 0 for row 
print("Array after deleting row 1 to 2 ", arr_2d_deleted)

arr_2d_deleted = np.delete(arr_2d_deleted, cols_to_dlt, axis = 1) # axis = 1 for column
print("Array after deleting column 1 to 2 ",arr_2d_deleted)

Array after deleting row 1 to 2  [[1 2 3]]
Array after deleting column 1 to 2  [[1]]
