## Numpy array and basics

In [1]:
import numpy as np

### creating array from list

In [3]:
arr_1d = np.array([1,2,3,4,5])
print("1D array: ", arr_1d)


arr_2d = np.array([ [1,2,3], 
                   [4,5,6] ])
print("2D array: ", arr_2d)




1D array:  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]


### List vs Numpy array

In [ ]:
py_list = [1, 2, 3]
print("Python list multiplication ", py_list * 2)

np_array = np.array([ 1, 2, 3])
print("Python array multiplication ", np_array * 2) # element wise multiplication or vectorized multiplication

Python list multiplication  [1, 2, 3, 1, 2, 3]
Python array multiplication  [2 4 6]


In [ ]:
import time
start = time.time()
py_list = [ i*2 for i in range(1000000)]
print("List operation time: ", time.time() - start)

start = time.time()
np_array =np.arange(1000000) * 2 # creates an array of elements from 0 to 99999 and then multiply each number by 2
print("\nNumpy operation time ", time.time() - start)

List operation time:  0.22011923789978027

Numpy operation time  0.008762598037719727


### creating array from scratch

In [13]:
zeros = np.zeros( (2, 4) )
print("zeros array: \n", zeros)

ones = np.ones((3, 4))
print("ones array: \n", ones)

# array with constant value
full = np.full((4, 4), 7)
print("full array: \n", full)

#array with random values 0 to 1
random = np.random.random( (2, 2) )
print("random array: \n", random )

sequence = np.arange(0, 10, 2)
print("sequence array \n", sequence)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full array: 
 [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
random array: 
 [[0.53004418 0.79174179]
 [0.32136347 0.64818927]]
sequence array 
 [0 2 4 6 8]


### Vector, Matrix and Tensor

In [16]:
vector = np.array([1, 2, 3])
print("Vector: \n", vector)

# Matrix - 2D array

matrix = np.array([ [1, 2,3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("Matrix: ", matrix)

# Tensor - More dimensions
tensor = np.array( [ [ [1, 2], [3, 4] ],
                    [ [5, 6], [7, 8]]])

print("Tensor: ", tensor)

Vector: 
 [1 2 3]
Matrix:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array properties

In [19]:
arr = np.array( [ [1, 2, 3],
                 [4, 5, 6]])

print("Shape ", arr.shape)
print("Dimension ", arr.ndim)
print("Size ", arr.size)
print("Dtype ", arr.dtype)


Shape  (2, 3)
Dimension  2
Size  6
Dtype  int64


### Array Reshaping

In [26]:
arr = np.arange(12)
print("Original array ", arr)

reshaped = arr.reshape(4, 3)
print("Reshaped array into 4 by 3 ", reshaped)

flatten = reshaped.flatten() # converts to 1 *  N array
print("Array is again flatten ", flatten)

#reval (returns view, instead of copy) s
raveled = reshaped.ravel()
print("raveled array: ", raveled)

# Transpose
transpose = reshaped.T
print("Transposed array ", transpose)

Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array into 4 by 3  [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Array is again flatten  [ 0  1  2  3  4  5  6  7  8  9 10 11]
raveled array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed array  [[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]
